apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: collector
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/zregvart-tenant/stackrox-collector/collector@sha256:ba4b0082e0f399e7dd351144cee75eb1f65e009dea118256cd8633df38e2479f
        name: my-python
        resources: {}
status: {}
