apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: collector
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: stackrox-collector
  name: collectorsirs
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: collector
    weight: null
status: {}
