apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: collector
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: stackrox-collector
  name: collector
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: collector
status:
  loadBalancer: {}
